### ISSUE TITLE
Entités html dans la description

### ISSUE THREAD

**Issue by Neamar** [Neamar/CineTime#129]
![Screenshot_20211002-142728](https://user-images.githubusercontent.com/536844/135748129-3f3df5ce-8aa3-4cff-933f-40e7119bc33a.png)

Il y a un nbsp; dans la description, peut on parser les entités html ?

**Comment by Nico04** [comment]
Je fais déjà un traitement mais effectivement j'ai pas pensé à ce style là. Tu peux regarder convertBasicHtmlTags dans le code et me dire si tu penses qu'il manque encore autre chose ?

**Comment by Neamar** [comment]
Je pense qu'on peut aussi rajouter un remplacement pour &nbsp; quitte à simplement le remplacer par une espace.

Sinon y a cette solution sans dépendance externe https://stackoverflow.com/a/61141254/1731144 en créant un faux span et en récupérant son innerText par le DOM, mais c'est probablement plus lourd.

**Comment by Nico04** [comment]
OK je replace l'espace aussi.
Par contre je déconseille l'autre solution car il faut importer TOUT 'dart:html', ce qui n'est pas rien je pense.

**Comment by Neamar** [comment]
y a pas du tree shaking à la compilation ? Il me semblait

**Comment by Nico04** [comment]
Si normalement c'est le cas effectivement.
=> Je vais juste faire l'espace, car je pense pas necessaire de se compliquer plus que ça
