### ISSUE TITLE
Feature request: Afficher la ville des cinémas sauvegardés

### ISSUE THREAD

**Issue by cdancette** [Neamar/CineTime#82]
Tout d'abord merci pour cette application très pratique,

Dans la liste des cinémas sauvegardés, il est indiqué l'adresse (numéro et rue) mais pas la ville. Quand on a beaucoup de cinémas, il est difficile de se souvenir dans quelle ville sont situés les cinémas. Le voir affiché dans la liste, après l'adresse serait très utile !

**Comment by Neamar** [comment]
Hello!

Malheureusement je ne maintiens plus l'application activement depuis quelques années, ayant bougé à l'étranger. Cela dit si tu as la motivation pour envoyer une pull request, j'intégrerai ça avec plaisir !
