### ISSUE TITLE
Afficher l'année de sortie du film

### ISSUE THREAD

**Issue by benitodeltorro** [Neamar/CineTime#85]
Merci beaucoup pour cette application qui est géniale.
La seule chose qui manque, selon moi, est l'année de sortie du film pour pouvoir facilement le situer (j'ai pas mal de cinémas indépendants par chez moi donc ça joue). Vu les infos que vous avez dans l'appli, je pense que l'année de sortie ne devrait pas être trop difficile à ajouter.
En tout cas merci d'avance.
Benjamin

**Comment by Neamar** [comment]
Hello,

L'année de sortie est maintenant affichée si le film ne date pas de l'année en cours :)
