### ISSUE TITLE
Keep a list of movies to watch

### ISSUE THREAD

**Issue by bnjbvr** [Neamar/CineTime#86]
Hi! Really love the app, I've been using it for years now, thanks for doing it!
There's one thing I'd love to see in this app: the ability to save movies that I'd like to watch in a side list, just by marking them as such. That would imply being able to remove them too at some point.
Would it make sense to add something like this?

**Comment by Neamar** [comment]
Hi! Thanks for your interest ;)

We're in the middle of a complete app refactoring, and will probably consider adding new features once we've pimped it a little :)

**Comment by bnjbvr** [comment]
So, no watch list I assume from the issue being closed? In any case it's totally fine, was just curious if it's been implemented or just not desired.

**Comment by Neamar** [comment]
Sorry, closed without posting comment. Yeah, decided to icebox this feature for now as we have major steps still to get the app to a better state. Once we're stable again, we can look at potential new features and decide which ones would make the more sense :)
